### ISSUE TITLE
Which product the code support for?

### ISSUE THREAD

**Issue by haonan-duan** [kylemathenia/Contactile_Data_Viz#1]
Hi Kylem, thanks for sharing your well-organized code! I am wondering which product your code supports for? I am recently using Contacile 3D force sensors (https://contactile.com/products/), is it same as what you are using?

**Comment by kylemathenia** [comment]
Hi there. I used this with there 3x3 v2 sensors.

**Comment by haonan-duan** [comment]
> Hi there. I used this with there 3x3 v2 sensors.

Thanks for your response.
